name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: yarn install --immutable
      - name: Build
        run: |
          # Generate the sitemap
          yarn build:sitemap
          # Build the PWA and the functions
          yarn build
        env:
          BROWSER_ENV: production
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Deploy
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_BASE64" | base64 --decode > firebase-service-account.json
          yarn firebase deploy --project ffb-ancillapp --config firebase.production.json --only hosting:ffb-ancillapp,functions:pwa
        env:
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64_PRODUCTION }}
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
      - name: Purge cache, audit, and report
        run: |
          # Install libgbm
          sudo apt-get -y install libgbm1
          # Install required libraries
          yarn add -D node-fetch@cjs lighthouse puppeteer node-telegram-bot-api
          # Run the postdeploy script
          node scripts/postdeploy
        env:
          REPORTER_BASE_URL: ${{ secrets.REPORTER_BASE_URL }}
          REPORTER_BOT_TOKEN: ${{ secrets.REPORTER_BOT_TOKEN }}
          REPORTER_CHAT_ID: ${{ secrets.REPORTER_CHAT_ID }}
          REPORTER_PROJECT_NAME: ${{ secrets.REPORTER_PROJECT_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
