name: Deploy to staging
on:
  push:
    branches:
      - develop
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install deps
        run: bun install
      - name: Build
        run: |
          bun run build:functions
          bun run build:sitemap
          bun run build:pwa --mode staging
        env:
          NODE_ENV: staging
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Deploy
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_BASE64" | base64 --decode > firebase-service-account.json
          echo "$FIREBASE_FUNCTIONS_DOTENV_BASE64" | base64 --decode > functions/.env.ancillapp-staging
          bun run firebase deploy --project ancillapp-staging --config firebase.json --only hosting:ancillapp-staging,functions:pwa
        env:
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64_STAGING }}
          FIREBASE_FUNCTIONS_DOTENV_BASE64: ${{ secrets.FIREBASE_FUNCTIONS_DOTENV_BASE64_STAGING }}
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
