name: Deploy to production
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install deps
        run: npm ci
      - name: Build
        run: |
          # Generate the sitemap
          npm run build:sitemap
          # Build the PWA and the functions
          BROWSER_ENV=production npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Deploy
        run: |
          npx firebase use --add ffb-ancillapp
          npx firebase deploy --token "$FIREBASE_TOKEN" --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Purge cache, audit, and report
        run: |
          # Install libgbm
          sudo apt-get -y install libgbm1
          # Install required libraries
          npm i -D node-fetch lighthouse puppeteer node-telegram-bot-api
          # Run the postdeploy script
          node scripts/postdeploy
        env:
          REPORTER_BASE_URL: ${{ secrets.REPORTER_BASE_URL }}
          REPORTER_BOT_TOKEN: ${{ secrets.REPORTER_BOT_TOKEN }}
          REPORTER_CHAT_ID: ${{ secrets.REPORTER_CHAT_ID }}
          REPORTER_PROJECT_NAME: ${{ secrets.REPORTER_PROJECT_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
